import { AMLTransaction } from '@/types/aml';
import { UnifiedUserData } from '@/context/compliance/types';

// Generate more realistic mock transaction data for assessment
export const generateMockTransactionData = (): AMLTransaction[] => [
  {
    id: 't1',
    senderName: 'John Doe',
    receiverName: 'ABC Corp Ltd',
    senderAmount: 15000,
    receiverAmount: 14500,
    senderCurrency: 'USD',
    receiverCurrency: 'EUR',
    senderCountryCode: 'US',
    receiverCountryCode: 'CH',
    method: 'wire_transfer',
    timestamp: new Date('2024-01-15').toISOString(),
    riskScore: 75,
    status: 'flagged',
    transactionId: 'TXN-001',
    category: 'cross_border',
  },
  {
    id: 't2',
    senderName: 'Maria Santos',
    receiverName: 'Crypto Exchange Inc',
    senderAmount: 50000,
    receiverAmount: 48500,
    senderCurrency: 'USD',
    receiverCurrency: 'BTC',
    senderCountryCode: 'BR',
    receiverCountryCode: 'US',
    method: 'crypto',
    timestamp: new Date('2024-01-14').toISOString(),
    riskScore: 85,
    status: 'under_review',
    transactionId: 'TXN-002',
    category: 'high_value',
  },
  {
    id: 't3',
    senderName: 'Tech Startup LLC',
    receiverName: 'Investment Fund',
    senderAmount: 250000,
    receiverAmount: 245000,
    senderCurrency: 'USD',
    receiverCurrency: 'USD',
    senderCountryCode: 'US',
    receiverCountryCode: 'LU',
    method: 'bank_transfer',
    timestamp: new Date('2024-01-13').toISOString(),
    riskScore: 45,
    status: 'approved',
    transactionId: 'TXN-003',
    category: 'business',
  }
];

export const generateMockUserData = (): UnifiedUserData[] => [
  {
    id: 'u1',
    fullName: 'Alice Johnson',
    email: 'alice.j@example.com',
    dateOfBirth: '1988-05-20',
    nationality: 'US',
    identityNumber: 'ID12345',
    phoneNumber: '+15551112222',
    address: '123 Main St, Anytown, USA',
    countryOfResidence: 'US',
    riskScore: 68,
    isPEP: false,
    isSanctioned: false,
    kycStatus: 'verified',
    createdAt: new Date('2023-01-01').toISOString(),
    kycFlags: {
      userId: 'u1',
      is_registered: true,
      is_email_confirmed: true,
      is_verified_pep: false,
      is_sanction_list: false,
      riskScore: 68,
    },
    documents: [],
    transactions: [],
    complianceCases: [],
    notes: [],
  },
  {
    id: 'u2',
    fullName: 'Bob Williams',
    email: 'bob.w@example.com',
    dateOfBirth: '1976-11-08',
    nationality: 'CA',
    identityNumber: 'ID67890',
    phoneNumber: '+15553334444',
    address: '456 Elm St, Toronto, CA',
    countryOfResidence: 'CA',
    riskScore: 92,
    isPEP: true,
    isSanctioned: false,
    kycStatus: 'pending',
    createdAt: new Date('2023-02-15').toISOString(),
    kycFlags: {
      userId: 'u2',
      is_registered: true,
      is_email_confirmed: true,
      is_verified_pep: true,
      is_sanction_list: false,
      riskScore: 92,
    },
    documents: [],
    transactions: [],
    complianceCases: [],
    notes: [],
  },
  {
    id: 'u3',
    fullName: 'Carlos Rodriguez',
    email: 'carlos.r@example.com',
    dateOfBirth: '1992-04-22',
    nationality: 'ES',
    identityNumber: 'ID13579',
    phoneNumber: '+34666777888',
    address: '789 Oak St, Madrid, ES',
    countryOfResidence: 'ES',
    riskScore: 34,
    isPEP: false,
    isSanctioned: false,
    kycStatus: 'rejected',
    createdAt: new Date('2023-03-10').toISOString(),
    kycFlags: {
      userId: 'u3',
      is_registered: true,
      is_email_confirmed: true,
      is_verified_pep: false,
      is_sanction_list: false,
      riskScore: 34,
    },
    documents: [],
    transactions: [],
    complianceCases: [],
    notes: [],
  },
];
